package controller

import (
	"fmt"
	"log/slog"
	"net/http"
	"sort"
	"strings"
	"time"

	"github.com/go-playground/validator/v10"
	"github.com/golang-jwt/jwt/v5"
	echojwt "github.com/labstack/echo-jwt/v4"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	slogecho "github.com/samber/slog-echo"
	echoSwagger "github.com/swaggo/echo-swagger"

	"github.com/drmaples/starter-app/app/platform"
	"github.com/drmaples/starter-app/docs" // docs generated by swag cli
)

// @title Sample App
// @version 1.0
// @description	some description here

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @BasePath /
// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name x-jwt-token

// GetServerAddress is address where server runs
func GetServerAddress() string {
	return fmt.Sprintf("%s:%d", platform.Config().ServerURL, platform.Config().ServerPort)
}

// GetServerBindAddress is bind address for echo server
func GetServerBindAddress() string {
	return fmt.Sprintf(":%d", platform.Config().ServerPort)
}

// Initialize sets up the controller layer
func Initialize() *echo.Echo {
	// programmatically set swagger info
	docs.SwaggerInfo.Host = strings.SplitAfter(GetServerAddress(), "://")[1]
	docs.SwaggerInfo.Schemes = []string{"http"}

	e := echo.New()
	if platform.Config().Environment != "dev" {
		e.HideBanner = true
		e.HidePort = true
	}
	e.Validator = newValidator()
	e.Use(slogecho.New(slog.Default()))
	e.Use(middleware.TimeoutWithConfig(middleware.TimeoutConfig{
		Timeout: 30 * time.Second,
	}))

	unrestricted := e.Group("")
	{
		unrestricted.GET("/", func(c echo.Context) error {
			return c.JSON(http.StatusOK, map[string]any{"howdy": "there"})
		})
		unrestricted.GET("/favicon.ico", func(c echo.Context) error { return nil }) // avoids 404 errors in the browser
		unrestricted.GET("/login", handleLogin)
		unrestricted.GET(oauthCallbackURL, handleOauthCallback)

		unrestricted.GET("/swagger/*", echoSwagger.WrapHandler)
		unrestricted.GET("/docs", func(c echo.Context) error {
			return c.Redirect(http.StatusTemporaryRedirect, "/swagger/index.html")
		})
	}

	restricted := e.Group("/v1")
	{
		restricted.Use(
			echojwt.WithConfig(echojwt.Config{
				SigningKey: []byte(platform.Config().JWTSignKey),
				NewClaimsFunc: func(c echo.Context) jwt.Claims {
					return new(jwtCustomClaims)
				},
				TokenLookup: "header:x-jwt-token",
			}),
		)
		restricted.GET("/user", handleListUsers)
		restricted.GET("/user/:id", handleGetUser)
		restricted.POST("/user", handleCreateUser)
	}

	// list routes in use like gin. keep at bottom
	if platform.Config().Environment == "dev" {
		allRoutes := e.Routes()
		sort.SliceStable(allRoutes, func(i, j int) bool {
			return allRoutes[i].Path < allRoutes[j].Path
		})
		for _, r := range allRoutes {
			fmt.Printf("[%-5s] %-35s --> %s\n", strings.ToUpper(r.Method), r.Path, r.Name)
		}
	}
	return e
}

type customValidator struct {
	validator *validator.Validate
}

func newValidator() echo.Validator {
	return &customValidator{validator: validator.New()}
}

func (cv *customValidator) Validate(i interface{}) error {
	return cv.validator.Struct(i)
}
